const hanziWordsArray = [
  { word: "我", pinyin: "wo", english: "I, me" },
  { word: "我们", pinyin: "women", english: "we, us (pl.)" },
  { word: "你", pinyin: "ni", english: "you" },
  { word: "他", pinyin: "ta", english: "he, him" },
  { word: "她", pinyin: "ta", english: "she, her" },
  { word: "这", pinyin: "zhe", english: "this" },
  { word: "那", pinyin: "na", english: "that" },
  { word: "哪", pinyin: "na", english: "which" },
  { word: "哪儿", pinyin: "nar", english: "where" },
  { word: "谁", pinyin: "shei", english: "who" },
  { word: "什么", pinyin: "shenme", english: "what" },
  { word: "多少", pinyin: "duoshao", english: "how many, how much" },
  { word: "几", pinyin: "ji", english: "how many" },
  { word: "怎么", pinyin: "zenme", english: "how" },
  { word: "怎么样", pinyin: "zenmeyang", english: "how about" },
  { word: "一", pinyin: "yi", english: "one" },
  { word: "二", pinyin: "er", english: "two" },
  { word: "三", pinyin: "san", english: "three" },
  { word: "四", pinyin: "si", english: "four" },
  { word: "五", pinyin: "wu", english: "five" },
  { word: "六", pinyin: "liu", english: "six" },
  { word: "七", pinyin: "qi", english: "seven" },
  { word: "八", pinyin: "ba", english: "eight" },
  { word: "九", pinyin: "jiu", english: "nine" },
  { word: "十", pinyin: "shi", english: "ten" },
  { word: "个", pinyin: "ge", english: "(measure word)" },
  { word: "岁", pinyin: "sui", english: "years old" },
  { word: "本", pinyin: "ben", english: "volume (book)" },
  { word: "些", pinyin: "xie", english: "some" },
  { word: "块", pinyin: "kuai", english: "piece, chunk" },
  { word: "不", pinyin: "bu", english: "not" },
  { word: "没", pinyin: "mei", english: "not (have)" },
  { word: "很", pinyin: "hen", english: "very" },
  { word: "太", pinyin: "tai", english: "too (much)" },
  { word: "都", pinyin: "dou", english: "all" },
  { word: "一点儿", pinyin: "yidianr", english: "a little bit" },
  { word: "和", pinyin: "he", english: "and" },
  { word: "在", pinyin: "zai", english: "at, in, on" },
  { word: "的", pinyin: "de", english: "possessive particle" },
  { word: "了", pinyin: "le", english: "completed action marker" },
  { word: "吗", pinyin: "ma", english: "question particle" },
  { word: "呢", pinyin: "ne", english: "question particle (contextual)" },
  { word: "喂", pinyin: "wei", english: "hello (on phone)" },
  { word: "家", pinyin: "jia", english: "home, family" },
  { word: "学校", pinyin: "xuexiao", english: "school" },
  { word: "饭店", pinyin: "fandian", english: "restaurant" },
  { word: "商店", pinyin: "shangdian", english: "shop, store" },
  { word: "医院", pinyin: "yiyuan", english: "hospital" },
  { word: "中国", pinyin: "zhongguo", english: "China" },
  { word: "北京", pinyin: "beijing", english: "Beijing" },
  { word: "上", pinyin: "shang", english: "up" },
  { word: "下", pinyin: "xia", english: "down" },
  { word: "前面", pinyin: "qianmian", english: "front" },
  { word: "后面", pinyin: "houmian", english: "behind" },
  { word: "里", pinyin: "li", english: "inside" },
  { word: "今天", pinyin: "jintian", english: "today" },
  { word: "明天", pinyin: "mingtian", english: "tomorrow" },
  { word: "昨天", pinyin: "zuotian", english: "yesterday" },
  { word: "上午", pinyin: "shangwu", english: "morning" },
  { word: "中午", pinyin: "zhongwu", english: "noon" },
  { word: "下午", pinyin: "xiawu", english: "afternoon" },
  { word: "年", pinyin: "nian", english: "year" },
  { word: "月", pinyin: "yue", english: "month" },
  { word: "号", pinyin: "hao", english: "day of month" },
  { word: "星期", pinyin: "xingqi", english: "week" },
  { word: "点", pinyin: "dian", english: "o'clock" },
  { word: "分钟", pinyin: "fenzhong", english: "minute" },
  { word: "现在", pinyin: "xianzai", english: "now" },
  { word: "时候", pinyin: "shihou", english: "time, moment" },
  { word: "爸爸", pinyin: "baba", english: "dad" },
  { word: "妈妈", pinyin: "mama", english: "mum" },
  { word: "儿子", pinyin: "erzi", english: "son" },
  { word: "女儿", pinyin: "nuer", english: "daughter" },
  { word: "老师", pinyin: "laoshi", english: "teacher" },
  { word: "学生", pinyin: "xuesheng", english: "student" },
  { word: "同学", pinyin: "tongxue", english: "classmate" },
  { word: "朋友", pinyin: "pengyou", english: "friend" },
  { word: "医生", pinyin: "yisheng", english: "doctor" },
  { word: "先生", pinyin: "xiansheng", english: "Mr." },
  { word: "小姐", pinyin: "xiaojie", english: "Miss" },
  { word: "衣服", pinyin: "yifu", english: "clothes" },
  { word: "水", pinyin: "shui", english: "water" },
  { word: "菜", pinyin: "cai", english: "dish" },
  { word: "米饭", pinyin: "mifan", english: "rice" },
  { word: "水果", pinyin: "shuiguo", english: "fruit" },
  { word: "苹果", pinyin: "pingguo", english: "apple" },
  { word: "茶", pinyin: "cha", english: "tea" },
  { word: "杯子", pinyin: "beizi", english: "cup" },
  { word: "钱", pinyin: "qian", english: "money" },
  { word: "飞机", pinyin: "feiji", english: "plane" },
  { word: "出租车", pinyin: "chuzuche", english: "taxi" },
  { word: "电视", pinyin: "dianshi", english: "TV" },
  { word: "电脑", pinyin: "diannao", english: "computer" },
  { word: "电影", pinyin: "dianying", english: "film" },
  { word: "天气", pinyin: "tianqi", english: "weather" },
  { word: "猫", pinyin: "mao", english: "cat" },
  { word: "狗", pinyin: "gou", english: "dog" },
  { word: "东西", pinyin: "dongxi", english: "thing" },
  { word: "人", pinyin: "ren", english: "person" },
  { word: "名字", pinyin: "mingzi", english: "name" },
  { word: "书", pinyin: "shu", english: "book" },
  { word: "汉语", pinyin: "hanyu", english: "Chinese" },
  { word: "字", pinyin: "zi", english: "character" },
  { word: "桌子", pinyin: "zhuozi", english: "table" },
  { word: "椅子", pinyin: "yizi", english: "chair" },
  { word: "谢谢", pinyin: "xiexie", english: "thank" },
  { word: "不客气", pinyin: "bukeqi", english: "you're welcome" },
  { word: "再见", pinyin: "zaijian", english: "goodbye" },
  { word: "请", pinyin: "qing", english: "please" },
  { word: "对不起", pinyin: "duibuqi", english: "sorry" },
  { word: "没关系", pinyin: "meiguanxi", english: "it doesn't matter" },
  { word: "是", pinyin: "shi", english: "to be" },
  { word: "有", pinyin: "you", english: "to have" },
  { word: "看", pinyin: "kan", english: "to look" },
  { word: "听", pinyin: "ting", english: "to listen" },
  { word: "说", pinyin: "shuo", english: "to speak" },
  { word: "读", pinyin: "du", english: "to read" },
  { word: "写", pinyin: "xie", english: "to write" },
  { word: "看见", pinyin: "kanjian", english: "to see" },
  { word: "叫", pinyin: "jiao", english: "to be called" },
  { word: "来", pinyin: "lai", english: "to come" },
  { word: "回", pinyin: "hui", english: "to return" },
  { word: "去", pinyin: "qu", english: "to go" },
  { word: "吃", pinyin: "chi", english: "to eat" },
  { word: "喝", pinyin: "he", english: "to drink" },
  { word: "睡觉", pinyin: "shuijiao", english: "to sleep" },
  { word: "打电话", pinyin: "dadianhua", english: "to call (on the phone)" },
  { word: "做", pinyin: "zuo", english: "to do" },
  { word: "买", pinyin: "mai", english: "to buy" },
  { word: "开", pinyin: "kai", english: "to open" },
  { word: "坐", pinyin: "zuo", english: "to sit" },
  { word: "住", pinyin: "zhu", english: "to live" },
  { word: "学习", pinyin: "xuexi", english: "to study" },
  { word: "工作", pinyin: "gongzuo", english: "to work" },
  { word: "下雨", pinyin: "xiayu", english: "to rain" },
  { word: "爱", pinyin: "ai", english: "to love" },
  { word: "喜欢", pinyin: "xihuan", english: "to like" },
  { word: "想", pinyin: "xiang", english: "to want to" },
  { word: "认识", pinyin: "renshi", english: "to know" },
  { word: "会", pinyin: "hui", english: "can" },
  { word: "能", pinyin: "neng", english: "can" },
  { word: "好", pinyin: "hao", english: "good" },
  { word: "大", pinyin: "da", english: "big" },
  { word: "小", pinyin: "xiao", english: "small" },
  { word: "多", pinyin: "duo", english: "many" },
  { word: "少", pinyin: "shao", english: "few" },
  { word: "冷", pinyin: "leng", english: "cold" },
  { word: "热", pinyin: "re", english: "hot" },
  { word: "高兴", pinyin: "gaoxing", english: "happy" },
  { word: "漂亮", pinyin: "piaoliang", english: "beautiful" }
];
